### ISSUE TITLE
Как выявляются предпочтения

### ISSUE THREAD

**Issue by barcacules111** [tpltn/similario#7]
История прослушиваний 
 |
Оценки «Нравится» и «Не нравится»
|
Пропуски треков (например, в альбоме, подборке или радио) и добавления треков в плейлисты
|
Положительные — прослушивание, оценка «Нравится», добавление в плейлист, а отрицательные — пропуск и оценка «Не нравится».

**Comment by tpltn** [comment]
@barcacules111 по большому счёту предпочтения сейчас - это всё то, что пользователь загрузил в сервис. Т.е. загрузка трека говорит о том, что он входит в твои предпочтения и рекомендации учитывают все твои предпочтения.
