### ISSUE TITLE
Как строится прогноз

### ISSUE THREAD

**Issue by barcacules111** [tpltn/similario#8]
Анализ профиля пользователя (музыкальных предпочтений)
|
Режим реального времени (новое действие — трек прослушан или добавлен в плейлист — профиль обновляется, и прогноз строится заново)
|
Учитывать другие объекты(треки, альбомы, исполнители, жанры)
|
Сравнивать профили всех пользователей(схожие музыкальные предпочтения)

**Comment by tpltn** [comment]
Режим реального времени есть в некотором смысле - при добавлении нового трека рекомендации автоматически пересчитаются. Всё другое - если вдруг успеет доделаться запланированное  ))
