### ISSUE TITLE
Как составляются рекомендации

### ISSUE THREAD

**Issue by barcacules111** [tpltn/similario#9]
Окончательный список рекомендаций составляется с помощью Матрикснета
|
Матрикснет обрабатывает список всех возможных рекомендаций
|
И в каком порядке их расположить

**Comment by tpltn** [comment]
@barcacules111 это что?)
Располагаются рекомендации в порядкке убывания количества похожих.
Например, для 3-x моих исполнителей похожей оказалась Sia, а от 2-x - Пицца. Соответственно будет
```
Sia: 3
Пицца: 2
```
Сия отобразится на первом месте
